import type { Metadata } from "next";
import { Breadcrumbs, PageHero } from "../components/SiteChrome";
import { pageMetadata } from "../lib/site";

export const metadata: Metadata = { ...pageMetadata("Privacyverklaring — concept", "Concept privacyverklaring voor het prototype van Van Dijk Rijschool.", "/privacy"), robots: { index: false, follow: false } };

export default function PrivacyPage() {
  return <main id="main-content"><PageHero eyebrow="Juridisch concept" title="Privacyverklaring" accent="voor het prototype." intro="Deze pagina beschrijft de beoogde gegevensverwerking. Voor livegang moet de tekst juridisch worden gecontroleerd en worden aangevuld met de echte bedrijfs- en leveranciersgegevens."><Breadcrumbs items={[{ label: "Privacy" }]} /></PageHero><section className="section"><article className="site-shell legal-copy"><p className="legal-warning">Concepttekst — niet gebruiken als definitieve juridische verklaring.</p><h2>1. Welke gegevens worden beoogd</h2><p>Bij een contact- of intakeaanvraag kunnen naam, contactgegevens, postcode, beschikbaarheid en vrijwillig verstrekte opmerkingen worden verwerkt. Het huidige prototype verzendt of bewaart deze gegevens niet.</p><h2>2. Doel van de verwerking</h2><p>De gegevens zijn bedoeld om vragen te beantwoorden, het lesgebied te controleren, een intake te plannen en—na inschrijving—de rijopleiding uit te voeren.</p><h2>3. NXTDRIVE en DriveYou</h2><p>Voor livegang wordt vastgelegd welke partijen verwerker, gezamenlijke verwerkingsverantwoordelijke of zelfstandig verantwoordelijke zijn. Ook bewaartermijnen en internationale doorgiften moeten dan expliciet worden beschreven.</p><h2>4. Cookies en statistieken</h2><p>Niet-noodzakelijke statistiek- en marketingcookies mogen pas na toestemming worden geladen. De productiesite krijgt een cookievoorkeurenscherm dat de daadwerkelijk gebruikte diensten weerspiegelt.</p><h2>5. Jouw rechten</h2><p>De definitieve verklaring beschrijft hoe betrokkenen inzage, correctie, verwijdering, beperking, overdraagbaarheid en bezwaar kunnen verzoeken.</p><h2>6. Contact en versie</h2><p>De officiële bedrijfsnaam, KvK-gegevens, contactgegevens, datum en versie worden vóór publicatie toegevoegd.</p></article></section></main>;
}

